name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # If on main branch, build and release image.
  release:
    if: github.event.base_ref == 'refs/heads/main'
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Branch name
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      
      - name: Create image tag
        run: echo "IMAGE_TAG=$(echo $SOURCE_TAG | sed 's/v//')" >> $GITHUB_ENV
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: artemshestakov/autofaq-webhook:${{ env.IMAGE_TAG }}